config/routes.rb
Rails.application.routes.draw do

  get 'login', to: 'sessions#new', as: 'login'

  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  resources :users

  resources :owner_verifications
  resources :proxy_votes_collected
  resources :buildings
  resources :annual_meetings
  root 'home#show'

end

app/models/annual_meeting.rb
# == Schema Information
#
# Table name: annual_meetings
#
#  id         :integer          not null, primary key
#  year       :integer
#  created_at :datetime
#  updated_at :datetime
#

class AnnualMeeting < ActiveRecord::Base
  validates_uniqueness_of :year
  validates_length_of :year, :minimum => 4, :maximum => 4, :allow_blank => false

  # def self.update_total_vote_count
  #   #get count from all my_collected votes for all buildings
  #   total_count = 0

  #   MyCollectedVote.all.each do |vote_collector|
  #     total_count += vote_collector.votes_collected
  #   end

  #   total_count
    
  # end

  # def self.vote_count_by_building

  #   # proxy_votes_by_building = [
  #   #   {:building_id => 1, :name => "365 Clinton", :building_votes => 22}
  #   # ]
  #   # currently ignoring year

  #   proxy_votes_by_building = []
  #   collected_votes = []
  #   buildings = Building.all
  #   collected_votes = MyCollectedVote.all

  #   # create array of hashes with building id and name
  #   proxy_votes_by_building = buildings.collect{|building| {:building_id => building.id, :building_name => building.name}}

  #   # for each building
  #   proxy_votes_by_building.each do |building|

  #     building[:building_votes] = 0

  #     #find all vote collectors for this building
  #     vote_collectors = MyCollectedVote.where :building_id => building[:building_id]

  #     vote_collectors.each do |vote_collector|
  #       building[:building_votes] += vote_collector.votes_collected
  #     end


  #     # sum up all votes from all vote collectors for each building 
  #     # building[:building_votes] = vote_collectors.collect{|vote_collector|{ vote_collector.votes_collected}}
  #   end

  #   proxy_votes_by_building

  # end
end

app/controllers/annual_meetings_controller.rb
class AnnualMeetingsController < ApplicationController
  before_action :set_annual_meeting, only: [:show, :edit, :update, :destroy]

  # GET /annual_meetings
  # GET /annual_meetings.json
  def index
    @annual_meetings = AnnualMeeting.all
  end

  # GET /annual_meetings/1
  # GET /annual_meetings/1.json
  def show
  end

  # GET /annual_meetings/new
  def new
    @annual_meeting = AnnualMeeting.new
  end

  # GET /annual_meetings/1/edit
  def edit
  end

  # POST /annual_meetings
  # POST /annual_meetings.json
  def create
    @annual_meeting = AnnualMeeting.new(annual_meeting_params)

    respond_to do |format|
      if @annual_meeting.save
        format.html { redirect_to @annual_meeting, notice: 'Annual meeting was successfully created.' }
        format.json { render :show, status: :created, location: @annual_meeting }
      else
        format.html { render :new }
        format.json { render json: @annual_meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /annual_meetings/1
  # PATCH/PUT /annual_meetings/1.json
  def update
    respond_to do |format|
      if @annual_meeting.update(annual_meeting_params)
        format.html { redirect_to @annual_meeting, notice: 'Annual meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @annual_meeting }
      else
        format.html { render :edit }
        format.json { render json: @annual_meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /annual_meetings/1
  # DELETE /annual_meetings/1.json
  def destroy
    @annual_meeting.destroy
    respond_to do |format|
      format.html { redirect_to annual_meetings_url, notice: 'Annual meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_annual_meeting
      @annual_meeting = AnnualMeeting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def annual_meeting_params
      params.require(:annual_meeting).permit(:year)
    end
end

app/helpers/annual_meetings_helper.rb
module AnnualMeetingsHelper
end

app/views/annual_meetings/_form.html.erb
<%= form_for(@annual_meeting) do |f| %>
  <% if @annual_meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@annual_meeting.errors.count, "error") %> prohibited this annual_meeting from being saved:</h2>

      <ul>
      <% @annual_meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/annual_meetings/edit.html.erb
<h1>Editing annual_meeting</h1>

<%= render 'form' %>

<%= link_to 'Show', @annual_meeting %> |
<%= link_to 'Back', annual_meetings_path %>

app/views/annual_meetings/index.html.erb
<h1>Listing annual_meetings</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @annual_meetings.each do |annual_meeting| %>
      <tr>
        <td><%= annual_meeting.year %></td>
        <td><%= link_to 'Show', annual_meeting %></td>
        <td><%= link_to 'Edit', edit_annual_meeting_path(annual_meeting) %></td>
        <td><%= link_to 'Destroy', annual_meeting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Annual meeting', new_annual_meeting_path %>

app/views/annual_meetings/new.html.erb
<h1>New annual_meeting</h1>

<%= render 'form' %>

<%= link_to 'Back', annual_meetings_path %>

app/views/annual_meetings/show.html.erb
<p>
  <strong>Year:</strong>
  <%= @annual_meeting.year %>
</p>

<%= link_to 'Edit', edit_annual_meeting_path(@annual_meeting) %> |
<%= link_to 'Back', annual_meetings_path %>