config/routes.rb
Rails.application.routes.draw do

  get 'login', to: 'sessions#new', as: 'login'

  
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  resources :users

  resources :owner_verifications
  resources :proxy_votes_collected
  resources :buildings
  resources :annual_meetings
  root 'home#show'

end

app/models/proxy_votes_collected.rb
# == Schema Information
#
# Table name: proxy_votes_collected
#
#  id                :integer          not null, primary key
#  annual_meeting_id :integer
#  building_id       :integer
#  user_id           :integer
#  votes_collected   :integer
#  created_at        :datetime
#  updated_at        :datetime
#

class ProxyVotesCollected < ActiveRecord::Base
end

app/controllers/proxy_votes_collected_controller.rb
class ProxyVotesCollectedController < ApplicationController
  before_action :set_proxy_votes_collected, only: [:show, :edit, :update, :destroy]

  # GET /proxy_votes_collected
  # GET /proxy_votes_collected.json
  def index
    @proxy_votes_collected = ProxyVotesCollected.all
  end

  # GET /proxy_votes_collected/1
  # GET /proxy_votes_collected/1.json
  def show
  end

  # GET /proxy_votes_collected/new
  def new
    @proxy_votes_collected = ProxyVotesCollected.new
  end

  # GET /proxy_votes_collected/1/edit
  def edit
  end

  # POST /proxy_votes_collected
  # POST /proxy_votes_collected.json
  def create
    @proxy_votes_collected = ProxyVotesCollected.new(proxy_votes_collected_params)

    respond_to do |format|
      if @proxy_votes_collected.save
        format.html { redirect_to @proxy_votes_collected, notice: 'Proxy votes collected was successfully created.' }
        format.json { render :show, status: :created, location: @proxy_votes_collected }
      else
        format.html { render :new }
        format.json { render json: @proxy_votes_collected.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proxy_votes_collected/1
  # PATCH/PUT /proxy_votes_collected/1.json
  def update
    respond_to do |format|
      if @proxy_votes_collected.update(proxy_votes_collected_params)
        format.html { redirect_to @proxy_votes_collected, notice: 'Proxy votes collected was successfully updated.' }
        format.json { render :show, status: :ok, location: @proxy_votes_collected }
      else
        format.html { render :edit }
        format.json { render json: @proxy_votes_collected.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proxy_votes_collected/1
  # DELETE /proxy_votes_collected/1.json
  def destroy
    @proxy_votes_collected.destroy
    respond_to do |format|
      format.html { redirect_to proxy_votes_collected_index_url, notice: 'Proxy votes collected was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proxy_votes_collected
      @proxy_votes_collected = ProxyVotesCollected.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proxy_votes_collected_params
      params.require(:proxy_votes_collected).permit(:annual_meeting_id, :building_id, :user_id, :votes_collected)
    end
end

app/helpers/proxy_votes_collected_helper.rb
module ProxyVotesCollectedHelper
end

app/views/proxy_votes_collected/_form.html.erb
<%= form_for(@proxy_votes_collected) do |f| %>
  <% if @proxy_votes_collected.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@proxy_votes_collected.errors.count, "error") %> prohibited this proxy_votes_collected from being saved:</h2>

      <ul>
      <% @proxy_votes_collected.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :annual_meeting_id %><br>
    <%= f.number_field :annual_meeting_id %>
  </div>
  <div class="field">
    <%= f.label :building_id %><br>
    <%= f.number_field :building_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :votes_collected %><br>
    <%= f.number_field :votes_collected %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/proxy_votes_collected/edit.html.erb
<h1>Editing proxy_votes_collected</h1>

<%= render 'form' %>

<%= link_to 'Show', @proxy_votes_collected %> |
<%= link_to 'Back', proxy_votes_collected_index_path %>

app/views/proxy_votes_collected/index.html.erb
<h1>Listing proxy_votes_collected</h1>

<table>
  <thead>
    <tr>
      <th>Annual meeting</th>
      <th>Building</th>
      <th>User</th>
      <th>Votes collected</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @proxy_votes_collected.each do |proxy_votes_collected| %>
      <tr>
        <td><%= proxy_votes_collected.annual_meeting_id %></td>
        <td><%= proxy_votes_collected.building_id %></td>
        <td><%= proxy_votes_collected.user_id %></td>
        <td><%= proxy_votes_collected.votes_collected %></td>
        <td><%= link_to 'Show', proxy_votes_collected %></td>
        <td><%= link_to 'Edit', edit_proxy_votes_collected_path(proxy_votes_collected) %></td>
        <td><%= link_to 'Destroy', proxy_votes_collected, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Proxy votes collected', new_proxy_votes_collected_path %>

app/views/proxy_votes_collected/new.html.erb
<h1>New proxy_votes_collected</h1>

<%= render 'form' %>

<%= link_to 'Back', proxy_votes_collected_index_path %>

app/views/proxy_votes_collected/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Annual meeting:</strong>
  <%= @proxy_votes_collected.annual_meeting_id %>
</p>

<p>
  <strong>Building:</strong>
  <%= @proxy_votes_collected.building_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @proxy_votes_collected.user_id %>
</p>

<p>
  <strong>Votes collected:</strong>
  <%= @proxy_votes_collected.votes_collected %>
</p>

<%= link_to 'Edit', edit_proxy_votes_collected_path(@proxy_votes_collected) %> |
<%= link_to 'Back', proxy_votes_collected_index_path %>